export TZ=Asia/Shanghai
export SSL_CERT_DIR="/system/etc/security/cacerts/"
export PATH=/data/adb/modules/Linlin/bin:$PATH

# 模块路径
module_dir="/data/adb/modules/Linlin"
# 日志路径
log_dir="${module_dir}/log"
# 用户
uid="root"
#组
gid="net_raw"
# DNS 重定向端口
redir_port=5591

# 开启AppOpt服务
enable_AppOpt="true"

# 开启adguardhome服务
enable_adguardhome="true"
# 是否阻断ipv6
block_ipv6_dns="false"
# 绕过源地址列表，用空格分隔
# list of source addresses to bypass, separated by spaces
ignore_src_list="172.19.0.1 172.18.0.1"
# 绕过目的地址列表，用空格分隔
# list of destination addresses to bypass, separated by spaces
ignore_dest_list=""

# 开启oxidns服务
enable_oxidns="true"

# 开启smartdns服务
enable_smartdns="true"

# 开启代理服务
enable_mihomo="true"
# 运行ruleconverter插件
enable_ruleconverter="true"
# ruleconverter插件运行端口
ruleconverter_port="9999"
# 运行模式：
# blacklist(指定应用不走代理)
# whitelist(仅指定应用走代理)
# global(全局代理)
# socks(仅运行核心不代理流量 使用核心的http/socks/mixed端口)
# 要指定的应用在packages.list填写包名每行一个(global模式不生效)
mode="blacklist"
mark_id="2025"
table_id="2025"
# ui端口
ui_prot="9090"
# API密码
secret="201314"
PACKAGES_LIST_FILE="${module_dir}/mihomoData/packages.list"
YAML_FILE="${module_dir}/conf/mihomo.yaml"
