bind-tcp 127.0.0.1:5445 -group home
bind 127.0.0.1:5445 -group home

bind-tcp 127.0.0.1:5555 -group office
bind 127.0.0.1:5555 -group office


dualstack-ip-selection yes
dualstack-ip-selection-threshold 200

response-mode fastest-ip
speed-check-mode ping,tcp:80,tcp:443

log-file /data/adb/modules/Linlin/log/smartdns.log
log-level info
log-size 2m
log-num 1

cache-size 65536
cache-persist yes  
cache-file /data/adb/modules/Linlin/cache/smartdns.cache
cache-checkpoint-time 1800  
  
serve-expired yes  
serve-expired-ttl 3600
serve-expired-reply-ttl 300
prefetch-domain yes
serve-expired-prefetch-time 3000

proxy-server socks5://127.0.0.1:7890 -name socks5

# ---------------------  
# 国内 home
server-tls 223.5.5.5 -group home -exclude-default-group
server-tls 223.6.6.6 -group home -exclude-default-group

# 国外 office（socks5）
server-tls 9.9.9.9 -group office -exclude-default-group -proxy socks5
server-tls 1.1.1.1 -group office -exclude-default-group -proxy socks5
server-tls 1.0.0.1 -group office -exclude-default-group -proxy socks5
server-tls 8.8.8.8 -group office -exclude-default-group -proxy socks5
server-tls 8.8.4.4 -group office -exclude-default-group -proxy socks5

# 数据目录
data-dir /data/adb/modules/Linlin/smartdnsData/data

# WebUI
plugin /data/adb/modules/Linlin/smartdnsData/smartdns_ui.so
smartdns-ui.www-root /data/adb/modules/Linlin/smartdnsData/wwwroot
smartdns-ui.ip http://127.0.0.1:6080
smartdns-ui.token-expire 600
smartdns-ui.max-query-log-age 86400
smartdns-ui.enable-terminal no
smartdns-ui.enable-cors yes
smartdns-ui.user root
smartdns-ui.password root