bind-tcp 127.0.0.1:5445 -group home
bind 127.0.0.1:5445 -group home

bind-tcp 127.0.0.1:5555 -group office -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa
bind 127.0.0.1:5555 -group office -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa


# TCP 空闲连接
tcp-idle-time 120
# 并发查询限制
max-query-limit 512

# Bootstrap 服务器
server 223.5.5.5 -bootstrap-dns -exclude-default-group
server 223.6.6.6 -bootstrap-dns -exclude-default-group


#验证证书
ca-file /data/adb/modules/Linlin/smartdnsData/Linlin.crt

#智能双栈优选
dualstack-ip-selection yes
dualstack-ip-selection-threshold 15
# 是否禁用ipv6
force-AAAA-SOA no
#是否允许纯IPV6地址
dualstack-ip-allow-force-AAAA yes

# 所有资源记录的 TTL
rr-ttl-min 5
rr-ttl-max 86400
rr-ttl-reply-max 60

# 响应过期请求时使用的 TTL 值
serve-expired-reply-ttl 5

#DNS64
dns64 64:ff9b::/96

#测试模式(最快ping:first-ping,最快ip:fastest-ip,最快响应:first-ping)
#response-mode fastest-ip
response-mode first-ping
#speed-check-mode ping,tcp:80,tcp:443
speed-check-mode tcp:443

#日志
log-file /data/adb/modules/Linlin/log/smartdns.log
log-level info
log-size 512k
log-num 1

audit-enable no
audit-num 16
audit-size 16M
audit-file /data/adb/modules/Linlin/log/smartdns-audit.log

#缓存
cache-size -1
#持久化缓存
cache-persist yes
cache-checkpoint-time 7200
cache-file /data/adb/modules/Linlin/cache/smartdns.cache

#域名预加载
prefetch-domain yes
#过期缓存
serve-expired yes
#过期缓存预获取时间
serve-expired-prefetch-time 21600
# 过期缓存超时时间
serve-expired-ttl 86400

#代理配置
proxy-server socks5://Linlin:201314@127.0.0.1:7890 -name socks5

# ---------------------
# 国内 home
server-tls dns.alidns.com -e -g home
server-tls dot.pub -e -g home
server-https https://dns.alidns.com/dns-query -e -g home
server-https https://doh.pub/dns-query -e -g home
server-quic dns.alidns.com -e -g home
server-http3 https://dns.alidns.com/dns-query -e -g home
server-http3 https://doh.pub/dns-query -e -g home

# 国外 office（socks5）
server-tls dns.quad9.net -e -g office -proxy socks5
server-tls one.one.one.one -e -g office -proxy socks5
server-tls dns.google -e -g office -proxy socks5
server-https https://cloudflare-dns.com/dns-query -e -g office -proxy socks5
server-https https://dns.google/dns-query -e -g office -proxy socks5
server-quic dns.quad9.net -e -g office -proxy socks5
server-http3 https://cloudflare-dns.com/dns-query -e -g office -proxy socks5
server-http3 https://dns.google/dns-query -e -g office -proxy socks5

#备用DNS
server-tcp 223.5.5.5 -fallback
server 223.5.5.5 -fallback

# 数据目录
data-dir /data/adb/modules/Linlin/smartdnsData/data

# WebUI
plugin /data/adb/modules/Linlin/smartdnsData/smartdns_ui.so
smartdns-ui.www-root /data/adb/modules/Linlin/smartdnsData/wwwroot
smartdns-ui.ip http://127.0.0.1:6080
smartdns-ui.token-expire 600
smartdns-ui.max-query-log-age 86400
smartdns-ui.enable-terminal no
smartdns-ui.enable-cors yes
smartdns-ui.user root
smartdns-ui.password root



