bind-tcp 127.0.0.1:5445 -group home
bind 127.0.0.1:5445 -group home

bind-tcp 127.0.0.1:5555 -group office
bind 127.0.0.1:5555 -group office


dualstack-ip-selection yes

response-mode fastest-ip
speed-check-mode ping

server 223.5.5.5 -bootstrap-dns

log-file /data/adb/modules/Linlin/log/smartdns.log
log-level info
log-size 2m
log-num 1

cache-size 65536
cache-persist yes  
cache-file /data/adb/modules/Linlin/cache/smartdns.cache
cache-checkpoint-time 1800  
  
serve-expired yes  
serve-expired-ttl 3600
serve-expired-reply-ttl 300
prefetch-domain yes
serve-expired-prefetch-time 3000

proxy-server socks5://127.0.0.1:7890 -name socks5

# ---------------------  
# 国内 home  
server-tls dns.alidns.com -host-ip 223.5.5.5 -host-name dns.alidns.com -tls-host-verify dns.alidns.com -g home -exclude-default-group

server-tls dns.alidns.com -host-ip 223.6.6.6 -host-name dns.alidns.com -tls-host-verify dns.alidns.com -g home -exclude-default-group

server-tls dns.alidns.com -host-ip 2400:3200::1 -host-name dns.alidns.com -tls-host-verify dns.alidns.com -g home -exclude-default-group

  
# 国外 office  
server-tls dns.google -host-ip 8.8.8.8 -host-name dns.google -tls-host-verify dns.google -g office -exclude-default-group -proxy socks5

server-tls cloudflare-dns.com -host-ip 1.1.1.1 -host-name cloudflare-dns.com -tls-host-verify cloudflare-dns.com -g office -exclude-default-group -proxy socks5

server-tls dns.quad9.net -host-ip 9.9.9.9 -host-name dns.quad9.net -tls-host-verify dns.quad9.net -g office -exclude-default-group -proxy socks5

server-tls cloudflare-dns.com -host-ip 2606:4700:4700::1111 -host-name cloudflare-dns.com -tls-host-verify cloudflare-dns.com -g office -exclude-default-group -proxy socks5

server-tls cloudflare-dns.com -host-ip 2606:4700:4700::1001 -host-name cloudflare-dns.com -tls-host-verify cloudflare-dns.com -g office -exclude-default-group -proxy socks5

server-tls dns.quad9.net -host-ip 2620:fe::fe -host-name dns.quad9.net -tls-host-verify dns.quad9.net -g office -exclude-default-group -proxy socks5
